# Generated by Django 4.1 on 2022-08-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Note",
            new_name="FizzBuzz",
        ),
    ]
